/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IEnspectionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isInspectorRegistered"
      | "registerInspector"
      | "removeInspector"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isInspectorRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerInspector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeInspector",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "isInspectorRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerInspector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeInspector",
    data: BytesLike
  ): Result;
}

export interface IEnspectionManager extends BaseContract {
  connect(runner?: ContractRunner | null): IEnspectionManager;
  waitForDeployment(): Promise<this>;

  interface: IEnspectionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isInspectorRegistered: TypedContractMethod<
    [inspeector: AddressLike],
    [boolean],
    "view"
  >;

  registerInspector: TypedContractMethod<
    [inspector: AddressLike],
    [void],
    "nonpayable"
  >;

  removeInspector: TypedContractMethod<
    [inspector: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isInspectorRegistered"
  ): TypedContractMethod<[inspeector: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerInspector"
  ): TypedContractMethod<[inspector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeInspector"
  ): TypedContractMethod<[inspector: AddressLike], [void], "nonpayable">;

  filters: {};
}
