/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iInspectionManagerSol from "./IInspectionManager.sol";
export type { iInspectionManagerSol };
export type { ICertificateNFT } from "./ICertificateNFT";
export type { ICertificationAuthority } from "./ICertificationAuthority";
export type { IEnterpriseRegistry } from "./IEnterpriseRegistry";
