/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICertificateNFT,
  ICertificateNFTInterface,
} from "../../../contracts/interfaces/ICertificateNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "enterprise",
        type: "address",
      },
    ],
    name: "getCertificateId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "certId",
        type: "uint256",
      },
    ],
    name: "isCertificateValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "enterprise",
        type: "address",
      },
      {
        internalType: "string",
        name: "metadataURI",
        type: "string",
      },
    ],
    name: "mintCertificate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "certId",
        type: "uint256",
      },
    ],
    name: "revokeCertificate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICertificateNFT__factory {
  static readonly abi = _abi;
  static createInterface(): ICertificateNFTInterface {
    return new Interface(_abi) as ICertificateNFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICertificateNFT {
    return new Contract(address, _abi, runner) as unknown as ICertificateNFT;
  }
}
