/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEnspectionManager,
  IEnspectionManagerInterface,
} from "../../../../contracts/interfaces/IInspectionManager.sol/IEnspectionManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "inspeector",
        type: "address",
      },
    ],
    name: "isInspectorRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "inspector",
        type: "address",
      },
    ],
    name: "registerInspector",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "inspector",
        type: "address",
      },
    ],
    name: "removeInspector",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEnspectionManager__factory {
  static readonly abi = _abi;
  static createInterface(): IEnspectionManagerInterface {
    return new Interface(_abi) as IEnspectionManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEnspectionManager {
    return new Contract(address, _abi, runner) as unknown as IEnspectionManager;
  }
}
